### ISSUE TITLE
初始化失败，提示:设置失败，将重试

### ISSUE THREAD

**Issue by ferdinandhuang016** [stackia/ha-deye-dehumidifier#50]
添加后，输入手机号和密码提示失败：
![image](https://github.com/user-attachments/assets/282dc0b4-aa16-406f-a3da-af24e0b69267)

Home Assistant版本：
Core
2024.12.4

日志如下：
`
2024-12-19 05:19:35.181 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f1388a0f260>,) inside the event loop by custom integration 'deye_dehumidifier' at custom_components/deye_dehumidifier/__init__.py, line 60: mqtt_client = DeyeMqttClient( (offender: /usr/local/lib/python3.13/site-packages/paho/mqtt/client.py, line 806: context.load_default_certs()), please create a bug report at https://github.com/stackia/ha-deye-dehumidifier/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 788, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/deye_dehumidifier/__init__.py", line 60, in async_setup_entry
    mqtt_client = DeyeMqttClient(

2024-12-19 05:44:21.193 DEBUG (MainThread) [custom_components.deye_dehumidifier.data_coordinator] Finished fetching deye_data_update_coordinator data in 0.445 seconds (success: True)
2024-12-19 05:44:31.457 DEBUG (MainThread) [custom_components.deye_dehumidifier.data_coordinator] Finished fetching deye_data_update_coordinator data in 10.263 seconds (success: False)

`

**Comment by zzhhxx** [comment]
一样的报错，等更新吧

**Comment by sususweet** [comment]
上面的报错只是个warning，我这边也有，但也能正常添加设备。

**Comment by stackia** [comment]
尝试更新一下 v1.6.3 试试

**Comment by ferdinandhuang016** [comment]
> 尝试更新一下 v1.6.3 试试

可以识别到设备了，非常感谢！
